name: Run Python Script and Create Executable

# Specify the environment where the script will run

on:
  push:
    branches:
      - main  # You can change this to your main branch name
env:
  python_version: 3.12.2
# Define the jobs to execute upon push
jobs:
    build:
      runs-on: ubuntu-latest
  # Define the steps to execute
      steps:
      - name: Install PyInstaller
        run: pip install pyinstaller
    
      - name: Run Python Script
        run: python script.py
    
      - name: Create Executable
        run: pyinstaller --onefile script.py
