name: Run Builder Batch File
on: [push]

jobs:
  run_batch_file:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Run Builder Batch File
      shell: cmd
      run: |
        call ./Python_Code/Builder.bat
