name: PyInstaller Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.0'
        
    - name: Install dependencies
      run: |
        pip install customtkinter
        pip install pyinstaller==6.1.0
        pip install pywin32
        pip install numpy
        pip install pillow==10.1.0
        pip install xlsxtpl
        pip install openpyxl==3.0.9
        pip install xltpl==0.19
        pip install wheel==0.41.2
        
    - name: Build executable
      run: |
        pyinstaller --windowed --hidden-import=tkinter --hidden-import=tkinter.filedialog --hidden-import=tkinter.font --hidden-import=distutils --hidden-import=customtkinter --icon=./Python_Code/Images/ship.ico ./Python_Code/AtoZ_Invoice.py
    - name: Release Executable
      uses: actions/upload-artifact@v3
      with:
          name: my-executable
          path: dist/AtoZ_Invoice.exe
