name: PyInstaller Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.2'
      
    - name: Install dependencies
      run: |
        pip install customtkinter
        pip install pyinstaller
        pip install pywin32
        pip install numpy
        pip install pillow
        pip install xlsxtpl
        pip install openpyxl==3.0.9
        pip install xltpl==0.19
        pip install wheel
        
    - name: Build executable
      run: |
        pyinstaller --windowed --hidden-import=tkinter --hidden-import=tkinter.filedialog --hidden-import=tkinter.font --hidden-import=distutils --hidden-import=customtkinter --icon=./Python_Code/Images/ship.ico ./Python_Code/AtoZ_Invoice.py
        xcopy /s /i .\Python_Code\Images     .\dist\AtoZ_Invoice\_internal\Images
        xcopy .\Python_Code\config.txt     .\dist\AtoZ_Invoice\_internal
        xcopy .\Python_Code\data.db     .\dist\AtoZ_Invoice\_internal
        xcopy .\Python_Code\template.xlsx     .\dist\AtoZ_Invoice\_internal
        
    - name: Signing
      uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.CERTPASS }}'
        folder: './dist'
        recursive: true

    - name: Release Executable
      uses: actions/upload-artifact@v4
      with:
          name: AtoZ_Invoice
          path: dist/
  release:
    name: Release project
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: AtoZ_Invoice
    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: AtoZ_Invoice.zip
    - name: Create GitHub release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      with:
        tag_name: '${{ github.run_number }}'
        release_name: Release '${{ github.run_number }}'
    - name: Upload release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      with:
        upload_url: '${{ steps.create-release.outputs.upload_url }}'
        asset_path: ./AtoZ_Invoice.zip
        asset_name: AtoZ_Invoice-v$${{ github.run_number }}.zip
        asset_content_type: application/zip
    - name:  second release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      with:
        upload_url: '${{ steps.create-release.outputs.upload_url }}'
        asset_path: ./dist/AtoZ_Invoice/AtoZ_Invoice.exe
        asset_name: AtoZ_Invoice-v$${{ github.run_number }}.zip
        asset_content_type: application
      
