name: PyInstaller Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --windowed --hidden-import=tkinter --hidden-import=tkinter.filedialog --hidden-import=tkinter.font --hidden-import=distutils --hidden-import=customtkinter --icon=./Python_Code/Images/ship.ico ./Python_Code/AtoZ_Invoice.py
    - name: Release Executable
      uses: actions/upload-artifact@v2
      with:
          name: my-executable
          path: dist/AtoZ_Invoice.exe
